### ISSUE TITLE
Error in the end of the command

### ISSUE THREAD

**Issue by lnjuanj** [kohheepeace/mr-pdf#44]
I have searched for the error on the Internet and this module reported issues, to no avail.

I run the following command:  
```
npx --loglevel verbose mr-pdf --initialDocURLs="https://v1.docusaurus.io/docs/en/installation" --contentSelector="article" --paginationSelector=".pagination-nav__item--next > a" --outputPDFFilename="nicefile.pdf" --coverTitle="My Title"
```

but always get the following error:

```
Downloading Chromium r722234 - 134.7 Mb [====================] 100% 0.0s

Retrieving html from https://v1.docusaurus.io/docs/en/installation

Success
Finish generating PDF!
Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\mygreatusername\AppData\Roaming\npm-cache\_npx\23396\node_modules\mr-pdf\node_modules\puppeteer\.local-chromium\win64-722234'
    at Object.rmdirSync (fs.js:916:10)
    at rmkidsSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:364:25)
    at rmdirSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:342:7)
    at rimrafSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:312:9)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:350:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:349:26)
    at rmdirSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:342:7)
    at rimrafSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:312:9)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:350:5
```

As you see, it always downloads chromium. I do not know if the pdf is the one that I was expecting (since it says "Finish generating PDF!"), but it does not look like so: The pdf is small, 3 pages, while the docusaurus installation takes +70 pages.

Thanks in advance!

**Comment by kohheepeace** [comment]
@lnjuanj  Hi

I just ran the below command, and it makes PDF correctly for v1 docusaurus site.
```
npx mr-pdf --initialDocURLs="https://v1.docusaurus.io/docs/en/installation" --paginationSelector=".docs-prevnext > a.docs-next" --excludeSelectors=".fixedHeaderContainer,footer.nav-footer,#docsNav,nav.onPageNav,a.edit-page-link,div.docs-prevnext" --cssStyle=".navPusher {padding-top: 0;}" --contentSelector="article"

```

> The pdf is small, 3 pages, while the docusaurus installation takes +70 pages.

=> Yes, because your are running mr-pdf toward official v1 docusaurus site by `--initialDocURLs="https://v1.docusaurus.io/docs/en/installation"`

You need to change this to your site initialDocURLs. or localhost URL is also working.

**Comment by kohheepeace** [comment]
Close due to no response.
